<?php echo '<?php'; ?>
<?php
use GI\RDB\ORM\Builder\View\Entity\Set\ClassView\ViewInterface;
/** @var ViewInterface $this */
?>

<?php $namespace = $this->getORMNamespace() . '\\' . $this->getTable()->getPhpNames()->getNamespace();?>
namespace <?php echo $namespace; ?>;

use <?php echo $this->getBaseNamespace(); ?>\AbstractSet as Base;

class Set extends Base implements SetInterface
{
    /**
     * @return RecordInterface
     */
    protected function createTemplateItem()
    {
        return $this->getORMFactory()-><?php echo $this->getTable()->getPhpNames()->getRecordCreator(); ?>();
    }

    /**
     * @param int $index
     * @return RecordInterface
     * @throws \Exception
     */
    public function get(int $index)
    {
        /** @var RecordInterface $result */
        $result = parent::get($index);

        return $result;
    }

    /**
     * @return RecordInterface
     * @throws \Exception
     */
    public function getFirst()
    {
        /** @var RecordInterface $result */
        $result = parent::getFirst();

        return $result;
    }

    /**
     * @return RecordInterface
     * @throws \Exception
     */
    public function getLast()
    {
        /** @var RecordInterface $result */
        $result = parent::getLast();

        return $result;
    }

    /**
     * @return RecordInterface[]
     * @throws \Exception
     */
    public function getItems()
    {
        /** @var RecordInterface[] $result */
        $result = parent::getItems();

        return $result;
    }
}