<?php
use GI\RDB\ORM\Builder\View\Entity\Record\Behaviour\ColumnBased\Property\ViewInterface;
/** @var ViewInterface $this */
$defaultValue = $this->getColumn()->getDefault();
if (empty($defaultValue) || ($defaultValue == 'current_timestamp()')) {
    $defaultValue = $this->getColumn()->isIntPHPType() ? 0 : '\'\'';
}
$null         = $this->getColumn()->isNull();
$default      = $null ? '' : ' = ' . $defaultValue;
$nullForDoc   = $this->getNullForDoc($this->getColumn());
?>
    /**
     * @var <?php echo $this->getColumn()->getPHPType(), $nullForDoc, PHP_EOL; ?>
     */
    private $<?php echo $this->getColumn()->getClassProperty(), $default; ?>;