<?php
use GI\RDB\ORM\Builder\View\Entity\Record\Behaviour\ColumnBased\Property\ViewInterface;
/** @var ViewInterface $this */
$defaultValue = $this->getColumn()->isIntPHPType() ? 0 : '\'\'';
$null         = $this->getColumn()->isNull();
$default      = $null ? '' : ' = ' . $defaultValue;
$nullForArg   = $this->getNullForDoc($this->getColumn());
?>
    /**
     * @var <?php echo $this->getColumn()->getPHPType(), $nullForArg, PHP_EOL; ?>
     */
    private $<?php echo $this->getColumn()->getClassProperty(), $default; ?>;