<?php echo '<?php'; ?>

<?php
    use GI\RDB\ORM\Builder\View\Entity\Set\InterfaceView\ViewInterface;
    /** @var ViewInterface $this */
?>

namespace <?php echo $this->getORMNamespace(), '\\', $this->getTable()->getNamespace(); ?>;

use <?php echo $this->getBaseNamespace(); ?>\SetInterface as BaseInterface;

interface SetInterface extends BaseInterface
{
    /**
     * @param int $index
     * @return RecordInterface
     * @throws \Exception
     */
    public function get(int $index);

    /**
     * @return RecordInterface
     * @throws \Exception
     */
    public function getFirst();

    /**
     * @return RecordInterface
     * @throws \Exception
     */
    public function getLast();

    /**
     * @return RecordInterface[]
     * @throws \Exception
     */
    public function getItems();
}