<?php
    /** @noinspection PhpUnhandledExceptionInspection */

    use GI\Component\Error\NotFound\View\ViewInterface;
    /** @var ViewInterface $this */
    echo $this->getResourceRenderer()->toString();
?>

<div>
    <div style="float: left">
        <img alt="Error" src="<?php echo $this->getResourceRenderer()->getImage(); ?>"
                                  data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="image" />
    </div>
    <div data-gi-css="<?php echo $this->getClientCSS()->toString(); ?>" data-gi-id="message" style="float: left">
        <?php echo $this->getMessage(); ?>
    </div>
    <div style="clear: both;"></div>
</div>