<?php
    /** @noinspection PhpUnhandledExceptionInspection */
    use GI\Application\Mock\NotFound\View\ViewInterface;
    /** @var ViewInterface $this */
?>

<html lang="en">
<head>
    <title><?php echo $this->getMessage(); ?></title>
    <style>
        * {font-size: 14px;}
        div.left {float: left;}
        div.clear {clear: both;}
        div.message {padding: 80px 0 0 20px; font-weight: bold; font-size: 30px;}
    </style>
</head>
    <div>
        <div class="left">
            <img src="<?php echo $this->createImageSource(); ?>" alt="Page not found" />
        </div>
        <div class="left message">
            <?php echo $this->getMessage(); ?>
        </div>
        <div class="clear"></div>
    </div>
<body>
</body>
</html>