<?php
/** @noinspection PhpUnhandledExceptionInspection */
use GI\RDB\ORM\Builder\View\Entity\Record\Behaviour\ColumnBased\Methods\ViewInterface;
/** @var ViewInterface $this */
?>
<?php
$column       = $this->getColumn();
$name         = $column->getName();
$type         = $column->getPHPType();
$property     = $column->getClassProperty();
$setter       = $column->getClassSetter();
$setterAccess = $this->getAccess($column);
$nullForDoc   = $this->getNullForDoc($column);
$nullForArg   = $this->getNullForArg($column);
?>
<?php echo $this->getGetterView()->toString(), PHP_EOL; ?>

    /**
     * @from-db <?php echo $name, PHP_EOL; ?>
     * @param <?php echo $type, $nullForDoc; ?> $<?php echo $property, PHP_EOL; ?>
     * @return static
     */
    <?php echo $setterAccess; ?> function <?php echo $setter; ?>(<?php echo $type; ?> $<?php echo $property, $nullForArg; ?>)
    {
        $this-><?php echo $property; ?> = (<?php echo $type; ?>)$<?php echo $property; ?>;

        return $this;
    }
<?php if ($column->isDatePHPType()): ?>

    /**
     * @return \DateTime
     * @throws \Exception
     */
    public function <?php echo $column->getClassDateGetter(); ?>()
    {
<?php if ($column->isIntPHPType()): ?>
        return new \DateTime('@' . $this-><?php echo $property; ?>);
<?php else: ?>
        return new \DateTime($this-><?php echo $property; ?>);
<?php endif;?>
    }
<?php endif;?>
<?php if ($column->isBoolPHPType()): ?>

    /**
     * @return bool
     */
    public function <?php echo $column->getClassBoolGetter(); ?>()
    {
        return (bool)$this-><?php echo $property; ?>;
    }
<?php endif;?>

