<?php echo '<?php'; ?>
<?php
use GI\RDB\ORM\Builder\View\Factory\ClassView\ViewInterface;
/** @var ViewInterface $this */
?>

<?php $namespace = $this->getORMNamespace(); ?>
namespace <?php echo $namespace; ?>\Factory;

use GI\RDB\ORM\Factory\AbstractFactory as Base;

<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
<?php $names = $table->getPhpNames(); ?>
use <?php echo $namespace; ?>\<?php echo $names->getRecordClass(); ?> as <?php echo $names->getRecordClassAlias(); ?>;
use <?php echo $namespace; ?>\<?php echo $names->getSetClass(); ?> as <?php echo $names->getSetClassAlias(); ?>;
<?php endforeach; ?>

use <?php echo $this->getServiceLocatorTrait(); ?> as ServiceLocatorAwareTrait;

<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
<?php $names = $table->getPhpNames(); ?>
use <?php echo $namespace; ?>\<?php echo $names->getRecordInterface(); ?> as <?php echo $names->getRecordInterfaceAlias(); ?>;
use <?php echo $namespace; ?>\<?php echo $names->getSetInterface(); ?> as <?php echo $names->getSetInterfaceAlias(); ?>;
<?php endforeach; ?>


/**
 * Class Factory
 * @package <?php echo $namespace; ?>\Factory
 *
<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
<?php $names = $table->getPhpNames(); ?>
 * @method <?php echo $names->getRecordInterfaceAlias() ?> <?php echo $names->getRecordCreator(); ?>()
 * @method <?php echo $names->getSetInterfaceAlias() ?> <?php echo $names->getSetCreator(); ?>()
<?php endforeach; ?>
 */
class Factory extends Base implements FactoryInterface
{
    use ServiceLocatorAwareTrait;


    /**
     * Factory constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        parent::__construct();

        $this
<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
<?php $names = $table->getPhpNames(); ?>
            ->setNamed('<?php echo $names->getRecordClassAlias(); ?>', <?php echo $names->getRecordClassAlias(); ?>::class)
            ->setNamed('<?php echo $names->getSetClassAlias(); ?>', <?php echo $names->getSetClassAlias(); ?>::class)
<?php endforeach; ?>
        ;
    }
}