<?php
    use GI\RDB\ORM\Builder\View\Factory\InterfaceView\ViewInterface;
    /** @var ViewInterface $this */
?>

namespace <?php echo $this->getORMNamespace(), '\\Factory'; ?>;

use GI\RDB\ORM\Factory\FactoryInterface as BaseInterface;

<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
    <?php
    $namespace = $this->getORMNamespace() . '\\' . $table->getNamespace();
    $alias     = $table->getAlias();
    ?>
use <?php echo $namespace, '\\RecordInterface'; ?> as <?php echo $alias, 'RecordInterface'; ?>;
use <?php echo $namespace, '\\SetInterface'; ?> as <?php echo $alias, 'SetInterface'; ?>;
<?php endforeach; ?>


interface FactoryInterface extends BaseInterface
{

}