<?php echo '<?php'; ?>
<?php
use GI\RDB\ORM\Builder\View\Factory\InterfaceView\ViewInterface;
/** @var ViewInterface $this */
?>

<?php $namespace = $this->getORMNamespace(); ?>
namespace <?php echo $namespace; ?>\Factory;

use GI\RDB\ORM\Factory\FactoryInterface as BaseInterface;

<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
<?php $names = $table->getPhpNames(); ?>
use <?php echo $namespace; ?>\<?php echo $names->getRecordInterface(); ?> as <?php echo $names->getRecordInterfaceAlias(); ?>;
use <?php echo $namespace; ?>\<?php echo $names->getSetInterface(); ?> as <?php echo $names->getSetInterfaceAlias(); ?>;
<?php endforeach; ?>


/**
 * Interface FactoryInterface
 * @package <?php echo $namespace; ?>\Factory
 *
<?php foreach ($this->getDriver()->getTableList()->getItems() as $table): ?>
<?php $names = $table->getPhpNames(); ?>
 * @method <?php echo $names->getRecordInterfaceAlias() ?> <?php echo $names->getRecordCreator(); ?>()
 * @method <?php echo $names->getSetInterfaceAlias() ?> <?php echo $names->getSetCreator(); ?>()
<?php endforeach; ?>
 */
interface FactoryInterface extends BaseInterface
{

}