<?php
/** @noinspection PhpUnhandledExceptionInspection */
use GI\RDB\ORM\Builder\View\Entity\Record\Behaviour\ColumnBased\Getter\ViewInterface;
/** @var ViewInterface $this */
?>
<?php
$column     = $this->getColumn();
$nullForArg = $this->getNullForDoc($column);
?>
    /**
     * @to-db <?php echo $column->getName(), PHP_EOL; ?>
     * @return <?php echo $column->getPHPType(), $nullForArg, PHP_EOL; ?>
<?php foreach ($column->getParentReferenceList()->getItems() as $referencedColumn): ?>
<?php $class = $referencedColumn->getTable()->getPhpNames()->getRecordClass(); ?>
     * @<?php echo $this->getORMNamespace(), '\\', $class; ?> <?php echo $referencedColumn->getName(), PHP_EOL; ?>
<?php endforeach; ?>
<?php foreach ($column->getChildReferenceList()->getItems() as $referencedColumn): ?>
<?php $class = $referencedColumn->getTable()->getPhpNames()->getSetClass();?>
     * @<?php echo $this->getORMNamespace(), '\\', $class; ?> <?php echo $referencedColumn->getName(), PHP_EOL; ?>
<?php endforeach; ?>
     */
    public function <?php echo $column->getClassGetter(); ?>()
    {
        return $this-><?php echo $column->getClassProperty(); ?>;
    }